#端口
server:
  port: 8101

spring:
  application:
    name: IoT-data-auth #应用名
  cloud:
    nacos: #注册中心
      discovery:
        server-addr: 192.168.10.197:8848

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
  sentinel:
    enabled: true